#!/usr/bin/env bash
# Build script: concatenates guide/*.md -> GUIDE.md (with TOC) and syncs
# chapter files + a manifest into web/content/ for the web adaptation.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=GUIDE.md
WEB_CONTENT=web/content
mkdir -p "$WEB_CONTENT"

# --- 1. Build GUIDE.md -------------------------------------------------------
{
  echo "<!-- AUTO-GENERATED by scripts/build.sh from guide/*.md — edit the chapter files, not this file. -->"
  echo
  first=1
  for f in guide/*.md; do
    if [[ $first -eq 1 ]]; then
      head -n 1 "$f"
      echo
      echo "## Table of Contents"
      echo
      for g in guide/*.md; do
        title=$(grep -m1 '^# ' "$g" | sed 's/^# //' || true)
        [[ -z "$title" ]] && title=$(grep -m1 '^## ' "$g" | sed 's/^## //')
        anchor=$(echo "$title" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9 -]//g; s/ +/-/g')
        echo "- [$title](#$anchor)"
      done
      echo
      tail -n +2 "$f"
      first=0
    else
      printf '\n\n---\n\n'
      cat "$f"
    fi
  done
} > "$OUT"

# --- 2. Sync chapters into web/content and write a manifest ------------------
rm -f "$WEB_CONTENT"/*.md
cp guide/*.md "$WEB_CONTENT"/

python3 - <<'PY'
import json, re, pathlib
files = sorted(pathlib.Path("guide").glob("*.md"))
manifest = []
for f in files:
    text = f.read_text(encoding="utf-8")
    m = re.search(r'^# (.+)$', text, re.M) or re.search(r'^## (.+)$', text, re.M)
    title = m.group(1).strip() if m else f.stem
    short = re.sub(r'^Chapter \d+ — ', '', title)
    manifest.append({"file": f.name, "title": title, "short": short, "words": len(text.split())})
pathlib.Path("web/content/manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"manifest: {len(manifest)} chapters, {sum(c['words'] for c in manifest)} words")
PY

echo "built $OUT ($(wc -w < "$OUT") words)"
