#!/usr/bin/env bash
# Build script: concatenates guide/*.md -> GUIDE.md (with TOC) and syncs
# chapter files + a manifest into web/content/ for the web adaptation.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=GUIDE.md
WEB_CONTENT=web/content
mkdir -p "$WEB_CONTENT"

# --- 1. Build GUIDE.md -------------------------------------------------------
{
  echo "<!-- AUTO-GENERATED by scripts/build.sh from guide/*.md — edit the chapter files, not this file. -->"
  echo
  first=1
  for f in guide/*.md; do
    if [[ $first -eq 1 ]]; then
      head -n 1 "$f"
      echo
      echo "## Table of Contents"
      echo
      for g in guide/*.md; do
        title=$(grep -m1 '^# ' "$g" | sed 's/^# //' || true)
        [[ -z "$title" ]] && title=$(grep -m1 '^## ' "$g" | sed 's/^## //')
        anchor=$(echo "$title" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9 -]//g; s/ +/-/g')
        echo "- [$title](#$anchor)"
      done
      echo
      tail -n +2 "$f"
      first=0
    else
      printf '\n\n---\n\n'
      cat "$f"
    fi
  done
} > "$OUT"

# --- 2. Sync chapters into web/content and write a manifest ------------------
rm -f "$WEB_CONTENT"/*.md
cp guide/*.md "$WEB_CONTENT"/

python3 - <<'PY'
import json, re, pathlib
files = sorted(pathlib.Path("guide").glob("*.md"))
manifest = []
for f in files:
    text = f.read_text(encoding="utf-8")
    m = re.search(r'^# (.+)$', text, re.M) or re.search(r'^## (.+)$', text, re.M)
    title = m.group(1).strip() if m else f.stem
    short = re.sub(r'^Chapter \d+ — ', '', title)
    overrides = {
        "00-intro.md": "Introduction & TL;DR",
        "13a-picks-tier1.md": "Picks by budget · Tier 1 · < $700",
        "13b-picks-tier2.md": "Tier 2 · $700–1,000",
        "13c-picks-tier3.md": "Tier 3 · $1,000–1,500",
        "13d-picks-tier4.md": "Tier 4 · $1,500–2,200",
        "13e-picks-tier5.md": "Tier 5 · $2,200+ & summary",
        "14a-personas-1.md": "Picks by persona · 1–6",
        "14b-personas-2.md": "Picks by persona · 7–14",
    }
    short = overrides.get(f.name, short)
    manifest.append({"file": f.name, "title": title, "short": short, "words": len(text.split())})
pathlib.Path("web/content/manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"manifest: {len(manifest)} chapters, {sum(c['words'] for c in manifest)} words")
PY

# --- 3. Sitemap (static routes + one entry per chapter) ------------------------
python3 - <<'PY'
import json, datetime
man = json.load(open("web/content/manifest.json"))
base = "https://gorg667.github.io/laptop-research/"
today = datetime.date.today().isoformat()
urls = [base, base + "#/compare", base + "#/finder", base + "#/about"] + [base + "#/ch/" + c["file"] for c in man] + [base + "GUIDE.md"]
xml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + "".join(f"  <url><loc>{u}</loc><lastmod>{today}</lastmod></url>\n" for u in urls) + "</urlset>\n"
open("web/sitemap.xml", "w").write(xml)
PY

echo "built $OUT ($(wc -w < "$OUT") words)"

# --- 4. Validate (schema, manifest sync, TOC anchors, finder scenarios) -------
if [[ "${SKIP_VALIDATE:-}" != "1" ]]; then python3 scripts/validate.py | tail -1; fi
